services:

  # ============================================================
  # BACKEND API
  # ============================================================

  - type: web
    name: cyclesense-api-ghcr
    runtime: image
    plan: free

    image:
      url: ghcr.io/ashlinleee/cyclesense-backend:latest
      creds:
        fromRegistryCreds:
          name: cyclesense-ghcr

    envVars:
      - key: PORT
        value: "8000"

      - key: PYTHONUNBUFFERED
        value: "1"

      - key: PYTHONDONTWRITEBYTECODE
        value: "1"

      - key: API_URL
        value: https://cyclesense-yjca.onrender.com

    healthCheckPath: /health


  # ============================================================
  # STREAMLIT FRONTEND
  # ============================================================

  - type: web
    name: cyclesense-frontend-ghcr
    runtime: image
    plan: free

    image:
      url: ghcr.io/ashlinleee/cyclesense-frontend:latest
      creds:
        fromRegistryCreds:
          name: cyclesense-ghcr

    envVars:
      - key: PORT
        value: "8501"

      - key: API_URL
        value: https://cyclesense-yjca.onrender.com

    healthCheckPath: /_stcore/health